#!/bin/bash
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --order=1 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=2 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=3 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=4 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=5 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=6 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=7 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=8 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=9 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=10 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=11 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=12 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=13 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=14 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=15 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=16 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=17 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=18 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=19 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=20 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=21 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=22 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=23 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=24 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=25 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=26 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=27 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=28 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=29 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=30 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=31 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=32 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=33 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=34 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=35 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=36 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=37 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=38 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=39 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=40 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=41 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=42 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=43 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=44 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=45 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=46 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=47 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=48 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=49 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=50 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=51 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=52 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=53 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=54 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=55 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=56 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=57 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=58 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=59 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=60 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=61 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=62 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=63 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=64 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=65 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=66 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=67 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=68 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=69 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=70 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=71 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=72 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=73 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=74 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=75 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=76 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=77 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=78 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=79 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=80 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=81 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=82 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=83 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=84 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=85 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=86 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=87 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=88 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=89 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=90 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=91 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=92 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=93 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-UnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=94 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-UnlockPickup-v0 --order=95 --total_timesteps=1000000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-Unlock-v0 --order=96 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=97 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=98 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-BlockedUnlockPickup-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=99 --total_timesteps=100000
python ppo_minigrid_chain.py --parent_folder=blocked_unlock_pickup_chain_mixed_2 --env_id=MiniGrid-Unlock-v0 --env_id_pre=MiniGrid-BlockedUnlockPickup-v0 --order=100 --total_timesteps=1000000
